name = "CoupledDipole"
uuid = "1aa92a3a-72ac-4ef3-9973-aaf9b373e3c1"
authors = ["Noel Araujo"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
