name: Runtests
on: [push, pull_request]
jobs:
  test:
    runs-os: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.8'
      - uses: julia-actions/julia-buildpkg@lastest
      - uses: julia-actions/julia-runtest@lastest